### PR TITLE
Support Anki 2.1.x

### PR DESCRIPTION
**Pull request by dae**
I haven't tested every feature, but adding cards and editing existing ones seems to work. The top level .py file is no longer required - you can just drop the image-occlusion-enhanced folder into the addons folder.

### CODE REVIEW

**Comment by glutanimate** [comment]
This is a tremendous contribution. Thank you, Damien!

From what I've seen so far, I can confirm that most core features are working fine, but I'll have to perform some more exhaustive tests once I find the time (currently still preparing for an exam, but I should be able to do this over the winter break and get an AnkiWeb release out).

For now I will be merging your changes into the anki2.1 branch.

**Comment by dae** [comment]
No problem, thank you for all your contributions to the Anki ecosystem, and best of luck on the exam :-)

**Comment by glutanimate** [comment]
The pleasure is all mine, and thanks! With Anki at my disposal it should hopefully be a breeze :+1:

**Comment by spacekitteh** [comment]
Perhaps upload it to ankiweb as a beta version? That way people can test it easier.

**Comment by glutanimate** [comment]
@spacekitteh definitely planning on doing that, but I ran into a few regressions I'd like to fix first.

**Comment by glutanimate** [comment]
@spacekitteh : Just released the first alpha of I/O Enhanced for Anki 2.1 on AnkiWeb: https://ankiweb.net/shared/info/1374772155. I would appreciate any help in testing it, if you have time :) !

**Pull request merged**
